# Generated by Django 4.1.2 on 2022-11-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MinhocaLoucaApp', '0009_alter_easyscore2_player_alter_hardscore2_player_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player2',
        ),
    ]
