# Generated by Django 4.1.2 on 2022-11-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MinhocaLoucaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
