# Generated by Django 4.1.2 on 2022-11-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MinhocaLoucaApp', '0004_alter_score_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='nickname',
            field=models.CharField(max_length=20),
        ),
    ]
