# Generated by Django 4.1.2 on 2022-11-27 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MinhocaLoucaApp', '0006_easyscore_hardscore_normalscore_delete_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player2',
            fields=[
                ('username', models.CharField(help_text='Entre com o nickname', max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Informe o Email', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NormalScore2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MinhocaLoucaApp.player2')),
            ],
        ),
        migrations.CreateModel(
            name='HardScore2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MinhocaLoucaApp.player2')),
            ],
        ),
        migrations.CreateModel(
            name='EasyScore2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MinhocaLoucaApp.player2')),
            ],
        ),
    ]
